syndication/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^eventsyndication/', include('webapp.urls')),
]

webapp/urls.py
#from django.conf.urls import url
#from . import views

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views
#from . import views

import oauth2client.contrib.django_util.site as django_util_site
from django.conf import urls
from . import forms
from . import views

urlpatterns = [
    #url(r'^$', views.index, name='index')
url(r'^$', views.home, name='home'),
    url(r'^createEvent$', views.createEvent, name='createEvent'),
    url(r'^admin', views.admin, name='admin'),
	url(r'^publish', views.publish, name='publish'),#/(?P<eventName>\d+)/$
	url(r'^pubStatus', views.pubStatus, name='pubStatus'),
    url(r'^login$', views.mylogin, name='login'),
    url(r'^logout$',views.logout_view,name='logout'),
    url(r'^apiKeys$', views.apiKeys, name='apiKeys'),
    url(r'^EBapiKeys$', views.EBapiKeys, name='EBapiKeys'),
    url(r'^syndicate$', views.syndicate, name='syndicate'),
    url(r'^profile_required$', views.get_profile_required),
    url(r'^groupManagement$',views.group_View, name='groupManagement'),
    url(r'^roleManagement$',views.role_View, name='roleManagement'),
    url(r'^oauth2/', urls.include(django_util_site.urls))

]

webapp/models.py
"""Definition of models"""
from django.db import models


class EventInfo(models.Model):

    """ This table will store the skeleton information about an event. To allow for
    repeatable events, this is separated from the table with the data about
     an individual trip."""
    EventName = models.CharField(max_length=50)
    EventDescription = models.TextField()
    PoCName = models.CharField(max_length=50, blank=True)
    PoCEmail = models.EmailField(max_length=100, blank=True)
    PoCNumber = models.CharField(max_length=15, blank=True)
    Fee = models.CharField(max_length=50, blank=True)
    Availability = models.CharField(max_length=50, blank=True)
    EventMeetLocation = models.CharField(max_length=50)
    EventDestination = models.CharField(max_length=50)
    EventStart = models.DateTimeField()
    EventEnd = models.DateTimeField()
    RegistrationLink = models.URLField()
    def __unicode__(self):
        return self.EventName


class ApiKey(models.Model):
    """Model for an API key"""
    service = models.CharField(max_length=50)
    key = models.TextField()
    lastUpdated = models.DateTimeField(auto_now_add=True)

    @classmethod
    def create(cls, service, key):
        """Method for creating a new API key"""
        apiKey = cls(service=service, key=key)
        return apiKey

class Services(models.Model):
    """Information regarding all available syndication services."""
    Name = models.CharField(max_length=50, blank=False)
    IsEnabled = models.BooleanField(default=True, blank=False)

class Publications(models.Model):
    """New model that keeps track of all instances of event publication"""
    EventID = models.ForeignKey(EventInfo, on_delete=models.CASCADE)
    Service = models.CharField(max_length=50, blank=False)
    Status = models.CharField(max_length=100)
    url = models.CharField(max_length=500)

    @classmethod
    def create(cls, EventID, Service):
        """Method to create new publication entry. Default status is pending"""
        publication=cls(EventID=EventID, Service=Service,Status='Pending')
        return publication

class LICCB_Role(models.Model):
    """Model for an internal role"""
    RoleName=models.CharField(max_length=256,blank=False)
    Groups=models.CharField(max_length=2048,blank=True)
    Users=models.CharField(max_length=2048,blank=True)
    CanLogin= models.BooleanField(default=True, blank=False)
    CreatePage_View=models.BooleanField(default=False, blank=False)
    CreatePage_Action=models.BooleanField(default=False, blank=False)
    PublishPage_View=models.BooleanField(default=False, blank=False)
    PublishPage_Action=models.BooleanField(default=False, blank=False)
    StatusPage_View=models.BooleanField(default=False, blank=False)
    StatusPage_Edit=models.BooleanField(default=False, blank=False)
    StatusPage_Delete=models.BooleanField(default=False, blank=False)
    CanChangePermissions=models.BooleanField(default=False, blank=False)
    CanChangeGroups=models.BooleanField(default=False, blank=False)
    CanChangeAPIKeys=models.BooleanField(default=False, blank=False) 
    CanViewLogs=models.BooleanField(default=False, blank=False)

#class LICCB_Relationship(models.Model):
#    RoleName=models.CharField(max_length=256)
#    childName=models.CharField(max_length=256)
#    childType=models.IntegerField()

class GlobalPermissions(models.Model):

    class Meta:
        managed = False  # No database table creation or deletion operations \
                         # will be performed for this model. 

        permissions = ( 
            ('CanLogin', 'Allows user to login'),  
            ('CreatePage_View', 'Can view the create page'), 
            ('CreatePage_Action', 'Can create events'), 
            ('PublishPage_View', 'Can view publish page'),  
            ('PublishPage_Action', 'Can publish events'), 
            ('StatusPage_View', 'Can view status of events'), 
            ('StatusPage_Edit', 'Can edit posted events'),  
            ('StatusPage_Delete', 'Can  delete posted events'), 
            ('CanChangePermissions', 'can change permissions'),  
            ('CanChangeGroups', 'Can change groups'), 
            ('CanChangeAPIKeys', 'Can change API keys'),
            ('CanViewLogs', 'Can view logs')
        )

webapp/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from webapp.models import EventInfo
from webapp.models import Services
from webapp.models import LICCB_Role

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))


class AddGroupForm(forms.Form):
    """ModelForm for Add group page."""
    groupName=forms.CharField(label='Group Name', max_length=50)
    Children=forms.CharField(label='Comma delimited users',max_length=256,required = False)   

class AddRoleForm(ModelForm):
    """ModelForm for Add Event page."""
    class Meta:
        model = LICCB_Role
        fields = [
        "RoleName",
    "Groups",
    "Users",
    "CanLogin",
    "CreatePage_View",
   "CreatePage_Action",
    "PublishPage_View",
    "PublishPage_Action",
    "StatusPage_View",
    "StatusPage_Edit",
    "StatusPage_Delete",
    "CanChangePermissions",
    "CanChangeGroups",
    "CanChangeAPIKeys",
    "CanViewLogs"
    ]


class AddEventForm(ModelForm):
    """ModelForm for Add Event page."""
    class Meta:
        model = EventInfo
        fields = [
            "EventName",
            "EventDescription",
            "PoCName",
            "PoCEmail",
            "PoCNumber",
            "Fee",
            "Availability",
            "EventMeetLocation",
            "EventDestination",
            "EventStart",
            "EventEnd",
            "RegistrationLink"
        ]
        labels = {
            "EventName":"Event Name",
            "EventDescription":"Description",
            "EventMeetLocation" : "Meet Location",
            "EventDestination" : "Destination",
            "EventStart" : "Start Time (MM/DD/YYYY HH:MM)",
            "EventEnd" : "End Time (MM/DD/YYYY HH:MM)",
            "PoCName":"Point of Contact's Name",
            "PoCEmail":"Point of Contact's Email",
            "PoCNumber":"Point of Contact's Number",
            "RegistrationLink":"Registration Link"
        }

class PublicationsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(PublicationsForm, self).__init__(*args, **kwargs)
        services = Services.objects.values_list('Name', flat=True)
        for service in services:
            self.fields[service] = forms.BooleanField(required=False)
    EventID = forms.IntegerField(widget=forms.HiddenInput())

webapp/templates/webapp/admin.html
{% extends "webapp/layout.html" %}

{% block content %}

{#<h1 class="pageHeader">{{ title }}</h1>#}
<div class="card">
    <h1 class="pageHeaders">{{ title }}</h1>
    <table id="AdminTable">
        <tr>
            <td>
                <i class="fa fa-lock"></i><br />
                <a href="{% url 'roleManagement' %}">Role and Permission Management</a>
            </td>
            <td>
                <i class="fa fa-key"></i>
                <br />
                <a href="apiKeys">Change API Keys </a>
            </td>
        </tr>
        <tr>
            <td>
                <i class="fa fa-group"></i><br />
                <a href="{% url 'groupManagement' %}">Manage Groups</a>
            </td>
            <td>
                <i class="fa fa-book"></i><br />
                <a href="#">View Logs</a>
            </td>
        </tr>
    </table>
</div>


{% endblock %}

webapp/templates/webapp/apiKeys.html
{% extends "webapp/layout.html" %}

{% block content %}

<div class="card">
    <h1 class="pageHeader">API Key Management Page</h1>
    <p>
    <h2>Facebook</h2>
    <p>(Log out and log back in to update API Key)</p>
    <a href="apiKeys?FBlogout=true">Logout</a> <br/>
    <a href="https://www.facebook.com/v2.8/dialog/oauth?client_id={{ FBclient_id }}&redirect_uri=http://{{ hostname }}/eventsyndication/apiKeys">Login</a> <br/>
    Current user: {{FBname}} <br/>
    </p>
    <hr>
    <h2>EventBrite</h2>
    <a href="EBapiKeys?EBlogout=true">Logout</a><br/>
    <a href="https://www.eventbrite.com/oauth/authorize?response_type=code&client_id={{ EBclient_id }}">Login</a><br/>
    Current user: {{EBname}}
    <br/><br/>
</div>

{% endblock %}

webapp/templates/webapp/createEvent.html
{% extends "webapp/layout.html" %}

{% block content %}

<div class="card">
    <h1 class="pageHeaders"> Create an Event </h1>
    <div class="cardBody">
        <br>
        <br>
        {% if not canAction %}
        <div class="alert alert-danger" style="text-align:center" role="alert">
            You don't have permission to create events. Please contact the admin if you believe you should have access.
        </div>
        {% endif %}
        {% if errorMessage %}
        <div class="alert alert-warning" style="text-align:center" role="alert">
            {{ errorMessage}}
        </div>
        {% endif %}
        <form method="post" action="publish">
            {% csrf_token %}
           
            {{ form.as_table }}
            {% if not canAction %}
            <input type="submit" value="Submit" disabled="disabled">
            {% else %}
            <input type="submit" value="Submit">
            {% endif %}
        </form>
    </div>
</div>
<!--<script src="../../static/webapp/scripts/createEventPage/pageActions.js" type="text/javascript"></script>-->
{% endblock %}

webapp/templates/webapp/groupManagement.html
{% extends "webapp/layout.html" %}

{% block content %}
{% if lastAction > 0 %}
<div class="alert alert-info" role="alert">
    {% if lastAction == 1 %}
    <b>Group Successfully Added</b>
    {% elif lastAction == 2 %}
    <b>Group Successfully Edited</b>
    {% elif lastAction == 3 %}
    <b>Group Successfully Deleted</b>
    {% endif %}
</div>
{% endif %}
<div class="card">
    <h1 class="pageHeaders"> Add A Group </h1>
    <div class="cardBody">
        <br>
        <br>
        <form method="post" action="groupManagement">
            {% csrf_token %}
            

              <!--{{ form.as_p }}-->
            <label for="groupName">Group Name</label>
            <input id="id_groupName" maxlength="256" name="groupName" required/>
            <br />
            <br />
            <label for="Children">Comma delimited list of users: </label>
            <textarea style="width:50%" id="Children" name="Children" maxlength="1024" required></textarea>
            <br />
            <br />
            <input type="submit" value="Add Group">
        </form>
    </div>
</div>
<div class="card">
    <h1 class="pageHeaders"> Edit Groups </h1>
    <div class="cardBody">
        <br>
        <br />
        <form method="post" action="groupManagement">
            {% csrf_token %}
            {% if not groups %}
            <div class="col-md-12">
                <h4 sstyle="text-align:center">No groups exist yet</h4>
            </div>
            {% else %}
            <select name="groupName">
                {% for group in groups %}

                <option value="{{group}}">{{group}}</option>

                {% endfor %}
            </select>
            <div id="test">
                <!--{{ form.as_p }}-->
                <!--<input id="id_groupName" maxlength="256" name="groupName" type="hidden" />-->
                <br />
                <label for="Children">Comma delimited list of users: </label>
                <textarea style="width:50%" id="Children" name="Children" maxlength="1024"></textarea>
            </div>
            <br />
            <input type="submit" value="Edit Group" name="editGroup">
			<input type="submit" value="Delete Group" name="deleteGroup">
            <!--<button id="deleteGroup">Delete Group</button>-->
            {% endif %}
        </form>
    </div>
</div>
<!--<script src="../../static/webapp/scripts/createEventPage/pageActions.js" type="text/javascript"></script>-->
{% endblock %}

webapp/templates/webapp/index.html
{% extends "webapp/layout.html" %}

{% block content %}

<div class="row">
    <div class="col-md-12" id="iframeWrapper">
        <br />
        <br />
        {% if errorMessage %}
        <div class="alert alert-danger" style="text-align:center" role="alert">
            {{errorMessage}}
            </div>
        {% endif %}
        <iframe src="https://calendar.google.com/calendar/embed?src=pfue9si6p7l6h81nuh8ft3oubk%40group.calendar.google.com&ctz=America/New_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
    </div>
</div>

{% endblock %}

webapp/templates/webapp/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{{ title }}</title>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'webapp/content/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'webapp/content/sidebar.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'webapp/content/site.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'webapp/content/card.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'PlugIns/font-awesome-4.7.0/css/font-awesome.min.css' %}" />
        {% comment %}
        <script src="{% static 'webapp/scripts/jquery-1.10.2.js' %}"></script>
        {% endcomment %}

        <script src="{% static 'webapp/scripts/bootstrap.min.js' %}"></script>
    </head>

<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/eventsyndication/" class="navbar-brand">Long Island City Community Boathouse Syndication Tool</a>
                {% if user.is_authenticated %}

                <a class="navbar-brand pull-right" style="float:right!important">Welcome {{ request.user.username }}!</a>

                <a href="/eventsyndication/logout" class="btn btn-default navbar-btn pull-right">Logout</a>
               
                {% else %}s
                <a href="/eventsyndication/login" class="btn btn-default navbar-btn pull-right">Login</a>
                {% endif %}
            </div>
            </div>
        </div>

        <div class="container body-content">
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li>
                        <a href="{% url 'createEvent' %}">Create Event</a>
                    </li>
                    <li>
                        <a href="{% url 'pubStatus' %}">Event Status</a>
                    </li>
                    <li>
                        <a href="{% url 'admin' %}">Administration</a>
                    </li>
                </ul>
            </div>

            {% block content %}{% endblock %}
            <hr/>
            <footer style="margin-left:250px">
                <p>&copy; {{ year }} - Long Island City Community Boathouse</p>
                <p><a href="https://github.com/LICCB/EventSyndication/issues">Report a Problem</a></p>
            </footer>
        </div>


        {% block scripts %}{% endblock %}

    </body>
</html>

webapp/templates/webapp/login.html
{% extends "webapp/layout.html" %}

{% block content %}

<div class="row">
    <div class="col-md-12 col-s-12">
        <section id="socialLoginForm">
            <h2>Login in using Google</h2>
            <form method="post">
                {% csrf_token %}
                <button type="submit">Login</button>
            </form>
        </section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'webapp/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

webapp/templates/webapp/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}

webapp/templates/webapp/logout.html
{% extends "webapp/layout.html" %}

{% block content %}

<div class="row">
    <div class="col-md-12 col-s-12">
        {% if errorMessage %}
        <br /><br />
        <div class="alert alert-danger" role="alert">
            {{errorMessage}}
            </div>
            {% endif %}
            <h2>You're logged out</h2>

        </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'webapp/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

webapp/templates/webapp/roleManagement.html
{% extends "webapp/layout.html" %}
{% block content %}
<style>
    table, th, td {
        border: 1px solid black;
        text-align: center;
        padding-right: 5px;
    }
</style>
{% if lastAction > 0 %}
<div class="alert alert-info" role="alert">
    {% if lastAction == 1 %}
    <b>Role Successfully Added</b>
    {% elif lastAction == 2 %}
    <b>Role Successfully Edited</b>
    {% elif lastAction == 3 %}
    <b>Role Successfully Deleted</b>
    {% endif %}
    </div>
{% endif %}
    <div class="card">
        <h1 class="pageHeaders"> Add A Role </h1>
        <div class="cardBody">
            <br>
            <br>

            <form method="post" action="roleManagement">
                {% csrf_token %}

                <div class="col-md-12">
                    <label for="RoleName">Role Name</label>
                    <input id="id_RoleName" maxlength="256" name="RoleName" required />
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-6">
                        <label for="Groups">Select Groups: </label>
                        <input style="width:80%" id="Groups" name="Groups" maxlength="1024" type="hidden" cardID="add">
                        <div class="checkBox conatiner" style="overflow-y: scroll;height:10%">
                            {% if not groups %}
                            <b> You have not created any groups yet</b>
                            Follow this link to create groups: <a href="{% url 'groupManagement' %}">Manage Groups</a>
                            {% else %}
                            {% for group in groups %}

                            <input type="checkbox" name="grpName" value="{{group}}"> {{group.name}}<br />

                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="Users">Comma delimited list of users: </label>
                        <textarea style="width:80%;height:10%" id="Users" name="Users" maxlength="1024"></textarea>
                    </div>

                </div>
                <br />
                <div class="col-md-12">
                    <table>
                        <thead>
                            <tr>
                                <th>Can Login</th>
                                <th colspan="2">Create Event</th>
                                <th colspan="2">Syndicate Event</th>
                                <th colspan="3">Published Event</th>
                                <th>Manage Groups</th>
                                <th>Manage Roles</th>
                                <th>Manage API Keys</th>
                                <th>View Logs</th>
                            </tr>
                            <tr>
                                <td></td>
                                <td>View</td>
                                <td>Action</td>
                                <td>View</td>
                                <td>Action</td>
                                <td>View</td>
                                <td>Edit</td>
                                <td>Delete</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input id="id_CanLogin" name="CanLogin" type="checkbox" checked></td>
                                <td><input id="id_CreatePage_View" name="CreatePage_View" type="checkbox"></td>
                                <td><input id="id_CreatePage_Action" name="CreatePage_Action" type="checkbox"></td>
                                <td><input id="id_PublishPage_View" name="PublishPage_View" type="checkbox"></td>
                                <td><input id="id_PublishPage_Action" name="PublishPage_Action" type="checkbox"></td>
                                <td><input id="id_StatusPage_View" name="StatusPage_View" type="checkbox"></td>
                                <td><input id="id_StatusPage_Edit" name="StatusPage_Edit" type="checkbox"></td>
                                <td><input id="id_StatusPage_Delete" name="StatusPage_Delete" type="checkbox"></td>
                                <td><input id="id_CanChangeGroups" name="CanChangeGroups" type="checkbox"></td>
                                <td><input id="id_CanChangePermissions" name="CanChangePermissions" type="checkbox"></td>
                                <td><input id="id_CanChangeAPIKeys" name="CanChangeAPIKeys" type="checkbox"></td>
                                <td><input id="id_CanViewLogs" name="CanViewLogs" type="checkbox"></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <br />
                <br />
                <input type="submit" value="Add Role">
            </form>
        </div>
    </div>
    <div class="card">
        <h1 class="pageHeaders">Edit Roles</h1>
        <div class="cardBody">
            <br>
            <br>
            <form method="post" action="roleManagement">
                {% csrf_token %}
                {% if not roles %}
                <div class="col-md-12">
                    <h4 sstyle="text-align:center">No roles exist yet</h4>
                </div>
                {% else %}

                <select name="RoleName" id="editSelector">
                    {% for role in roles %}

                    <option value="{{role.RoleName}}">{{role.RoleName}}</option>

                    {% endfor %}
                </select>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-6">
                        <label for="Groups">Select Groups: </label>
                        <input style="width:80%" id="Groups" name="Groups" maxlength="1024" type="hidden" cardID="edit">
                        <div class="checkBox conatiner" style="overflow-y: scroll;height:10%">
                            {% if not groups %}
                            <b> You have not created any groups yet</b>
                            Follow this link to create groups: <a href="{% url 'groupManagement' %}">Manage Groups</a>
                            {% else %}
                            {% for group in groups %}

                            <input type="checkbox" name="editgrpName" value="{{group}}"> {{group.name}}<br />

                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="Users">Comma delimited list of users: </label>
                        <textarea style="width:80%;height:10%" id="Users" name="Users" maxlength="1024" toedit="true"></textarea>
                    </div>

                </div>
                <br />
                <div class="col-md-12">
                    <table>
                        <thead>
                            <tr>
                                <th>Can Login</th>
                                <th colspan="2">Create Event</th>
                                <th colspan="2">Syndicate Event</th>
                                <th colspan="3">Published Event</th>
                                <th>Manage Groups</th>
                                <th>Manage Roles</th>
                                <th>Manage API Keys</th>
                                <th>View Logs</th>
                            </tr>
                            <tr>
                                <td></td>
                                <td>View</td>
                                <td>Action</td>
                                <td>View</td>
                                <td>Action</td>
                                <td>View</td>
                                <td>Edit</td>
                                <td>Delete</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr id="EditRoleRow">
                                <!--{% if roles[]}-->
                                <td><input id="id_CanLogin" name="CanLogin" type="checkbox"></td>
                                <td><input id="id_CreatePage_View" name="CreatePage_View" type="checkbox"></td>
                                <td><input id="id_CreatePage_Action" name="CreatePage_Action" type="checkbox"></td>
                                <td><input id="id_PublishPage_View" name="PublishPage_View" type="checkbox"></td>
                                <td><input id="id_PublishPage_Action" name="PublishPage_Action" type="checkbox"></td>
                                <td><input id="id_StatusPage_View" name="StatusPage_View" type="checkbox"></td>
                                <td><input id="id_StatusPage_Edit" name="StatusPage_Edit" type="checkbox"></td>
                                <td><input id="id_StatusPage_Delete" name="StatusPage_Delete" type="checkbox"></td>
                                <td><input id="id_CanChangeGroups" name="CanChangeGroups" type="checkbox"></td>
                                <td><input id="id_CanChangePermissions" name="CanChangePermissions" type="checkbox"></td>
                                <td><input id="id_CanChangeAPIKeys" name="CanChangeAPIKeys" type="checkbox"></td>
                                <td><input id="id_CanViewLogs" name="CanViewLogs" type="checkbox"></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <br />
                <br />
                <input type="submit" value="Edit Role" name="editRole">
                <input type="submit" value="Delete Role" name="deleteRole">
                {% endif %}
            </form>
        </div>
    </div>
    <script>
        $('input[name="grpName"]').change(function () {
            var gName = this.value;
            if (this.checked) {

                $('input[cardID="add"]').each(function (e) {
                    this.value += gName + ",";
                })
            }
            else {
                $('input[cardID="add"]').each(function (e) {
                    this.value = this.value.replace(gName + ",", "");
                })
            }
        })
        $('input[name="editgrpName"]').change(function () {
            var gName = this.value;
            if (this.checked) {

                $('input[cardID="edit"]').each(function (e) {
                    this.value += gName + ",";
                })
            }
            else {
                $('input[cardID="edit"]').each(function (e) {
                    this.value = this.value.replace(gName + ",", "");
                })
            }
        })
        function onSelectorChange(rolePK, roles) {
            alert(rolePK);
            alert(roles.length)
        }
    </script>
    <!--<script src="../../static/webapp/scripts/createEventPage/pageActions.js" type="text/javascript"></script>-->
    {% endblock %}